"""initial

Revision ID: fa74ef61515f
Revises: 
Create Date: 2026-03-05 14:34:35.652086

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fa74ef61515f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('productid', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_productid'), 'inventory_items', ['productid'], unique=False)
    op.create_index(op.f('ix_inventory_items_timestamp'), 'inventory_items', ['timestamp'], unique=False)
    op.create_index('ix_inventory_productid_timestamp', 'inventory_items', ['productid', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventory_productid_timestamp', table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_timestamp'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_productid'), table_name='inventory_items')
    op.drop_table('inventory_items')
    # ### end Alembic commands ###
